remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Nkeiru Personal Site
logo: assets/img/Nkeiru_LinkedIn_2.jpg
description: Personal site under construction
show_downloads: false
