remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Nkeriu Personal Site
logo: assets/img/Nkeiru_LinkedIn_2.jpg
description: PErsonal site under construction
show_downloads: true
